name = "hat_pull"
version = "0.0.1"
licences = ["MIT"]
description = "Pull a name out of a hat, automated in Gleam."
links = { title = 'GitHub', href = 'https://github.com/noamsauerutley/hat-pull' }
repository = { type = "github", user = "noamsauerutley", repo = "hat-pull" }

[dependencies]
gleam_stdlib = "~> 0.21"

[dev-dependencies]
gleeunit = "~> 0.6"
