name = "hat"
version = "0.0.1"
licences = ["MIT"]
description = "Pull a name out of a hat, automated in Gleam."

[docs]
links = [
  { title = 'GitHub', href = 'https://github.com/noamsauerutley/noamsauerutley' }
]

[repository]
type = "github"
user = "noamsauerutley"
repo = "noamsauerutley"

[dependencies]
gleam_stdlib = "~> 0.21"

[dev-dependencies]
gleeunit = "~> 0.6"
